<?php

$likert4 = [
    0 => 'Absolutamente não',
    1 => 'Levemente',
    2 => 'Moderadamente',
    3 => 'Gravemente',
];

$frequency4 = [
    0 => 'Nunca',
    1 => 'Raramente',
    2 => 'Às vezes',
    3 => 'Frequentemente',
];

return [
    'bai' => [
        'label' => 'Escala de Ansiedade (BAI)',
        'short_label' => 'BAI',
        'description' => 'Inventário de Ansiedade de Beck — triagem de sintomas somáticos e cognitivos de ansiedade.',
        'max_score' => 63,
        'options' => $likert4,
        'questions' => [
            ['key' => 'q01', 'text' => 'Entorpecido ou formigamento'],
            ['key' => 'q02', 'text' => 'Sensação de calor'],
            ['key' => 'q03', 'text' => 'Tremor nas pernas'],
            ['key' => 'q04', 'text' => 'Incapaz de relaxar'],
            ['key' => 'q05', 'text' => 'Medo de que aconteça o pior'],
            ['key' => 'q06', 'text' => 'Tonto ou atordoado'],
            ['key' => 'q07', 'text' => 'Coração acelerado ou disparado'],
            ['key' => 'q08', 'text' => 'Instável'],
            ['key' => 'q09', 'text' => 'Aterrorizado ou apavorado'],
            ['key' => 'q10', 'text' => 'Nervoso'],
            ['key' => 'q11', 'text' => 'Sensação de asfixia'],
            ['key' => 'q12', 'text' => 'Tremor nas mãos'],
            ['key' => 'q13', 'text' => 'Corpo tenso ou rígido'],
            ['key' => 'q14', 'text' => 'Medo de perder o controle'],
            ['key' => 'q15', 'text' => 'Dificuldade para respirar'],
            ['key' => 'q16', 'text' => 'Medo de morrer'],
            ['key' => 'q17', 'text' => 'Assustado'],
            ['key' => 'q18', 'text' => 'Indigestão ou desconforto abdominal'],
            ['key' => 'q19', 'text' => 'Desmaio'],
            ['key' => 'q20', 'text' => 'Rosto ruborizado'],
            ['key' => 'q21', 'text' => 'Suor (não devido ao calor)'],
        ],
        'bands' => [
            ['max' => 7, 'label' => 'Ansiedade mínima', 'severity' => 'minimal', 'risk' => false],
            ['max' => 15, 'label' => 'Ansiedade leve', 'severity' => 'mild', 'risk' => false],
            ['max' => 25, 'label' => 'Ansiedade moderada', 'severity' => 'moderate', 'risk' => true],
            ['max' => 63, 'label' => 'Ansiedade grave', 'severity' => 'severe', 'risk' => true],
        ],
    ],

    'bdi' => [
        'label' => 'Escala de Depressão (BDI)',
        'short_label' => 'BDI',
        'description' => 'Inventário de Depressão de Beck — triagem de sintomas depressivos nas últimas duas semanas.',
        'max_score' => 63,
        'options' => $likert4,
        'questions' => [
            ['key' => 'q01', 'text' => 'Tristeza'],
            ['key' => 'q02', 'text' => 'Pessimismo'],
            ['key' => 'q03', 'text' => 'Sensação de fracasso'],
            ['key' => 'q04', 'text' => 'Perda de prazer'],
            ['key' => 'q05', 'text' => 'Sentimentos de culpa'],
            ['key' => 'q06', 'text' => 'Expectativa de punição'],
            ['key' => 'q07', 'text' => 'Autoaversão'],
            ['key' => 'q08', 'text' => 'Autocrítica'],
            ['key' => 'q09', 'text' => 'Pensamentos ou desejos suicidas'],
            ['key' => 'q10', 'text' => 'Choro'],
            ['key' => 'q11', 'text' => 'Agitação'],
            ['key' => 'q12', 'text' => 'Perda de interesse'],
            ['key' => 'q13', 'text' => 'Indecisão'],
            ['key' => 'q14', 'text' => 'Sensação de inutilidade'],
            ['key' => 'q15', 'text' => 'Perda de energia'],
            ['key' => 'q16', 'text' => 'Alterações no padrão de sono'],
            ['key' => 'q17', 'text' => 'Irritabilidade'],
            ['key' => 'q18', 'text' => 'Alterações no apetite'],
            ['key' => 'q19', 'text' => 'Dificuldade de concentração'],
            ['key' => 'q20', 'text' => 'Cansaço ou fadiga'],
            ['key' => 'q21', 'text' => 'Perda de interesse por sexo'],
        ],
        'bands' => [
            ['max' => 11, 'label' => 'Depressão mínima', 'severity' => 'minimal', 'risk' => false],
            ['max' => 19, 'label' => 'Depressão leve', 'severity' => 'mild', 'risk' => false],
            ['max' => 35, 'label' => 'Depressão moderada', 'severity' => 'moderate', 'risk' => true],
            ['max' => 63, 'label' => 'Depressão grave', 'severity' => 'severe', 'risk' => true],
        ],
    ],

    'stress' => [
        'label' => 'Escala de Estresse',
        'short_label' => 'Estresse',
        'description' => 'Triagem de percepção de estresse nas últimas semanas (10 itens).',
        'max_score' => 30,
        'options' => $frequency4,
        'questions' => [
            ['key' => 'q01', 'text' => 'Sentiu-se sobrecarregado(a) com responsabilidades'],
            ['key' => 'q02', 'text' => 'Dificuldade para controlar preocupações'],
            ['key' => 'q03', 'text' => 'Irritação ou impaciência frequente'],
            ['key' => 'q04', 'text' => 'Dificuldade para relaxar'],
            ['key' => 'q05', 'text' => 'Tensão muscular ou dores relacionadas ao estresse'],
            ['key' => 'q06', 'text' => 'Alterações no sono por preocupação'],
            ['key' => 'q07', 'text' => 'Sensação de esgotamento emocional'],
            ['key' => 'q08', 'text' => 'Dificuldade de concentração por estresse'],
            ['key' => 'q09', 'text' => 'Sentiu que não dava conta das demandas'],
            ['key' => 'q10', 'text' => 'Percebeu o estresse a interferir no dia a dia'],
        ],
        'bands' => [
            ['max' => 9, 'label' => 'Estresse baixo', 'severity' => 'minimal', 'risk' => false],
            ['max' => 18, 'label' => 'Estresse moderado', 'severity' => 'moderate', 'risk' => true],
            ['max' => 30, 'label' => 'Estresse elevado', 'severity' => 'severe', 'risk' => true],
        ],
    ],
];
